version: "2"

services:

  nginx:
    container_name: nginx-tclawnlex
    image: kyma/docker-nginx
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tclawnlex-network

networks:
  tclawnlex-network:
    driver: bridge
